export const REQ_START = 'REQ_START';
export const REQ_SUCCESS = 'REQ_SUCCESS';
export const REQ_LIST_SUCCESS = 'REQ_LIST_SUCCESS';
export const REQ_FAIL = 'REQ_FAIL';
export const SAVE_BUCKET_SUCCESS = 'SAVE_BUCKET_SUCCESS';
export const SAVE_LIST_SUCCESS = 'SAVE_LIST_SUCCESS';